### ISSUE TITLE
Inconsistent server response when requesting for access token

### ISSUE THREAD

**Issue by rsong6** [jasonjoh/python_clientcred#5] opened 2016-07-20 19:24 UTC
I followed your example to implement the client credential flow using Python but I keep getting inconsistent server responses when I try to request for an access token. I was wondering if you could please provide some insight into the issue. When the request fails, it returns a 401 saying that client assertion contains an invalid signature. If that was the case, how was I able to get access tokens before and after the request?

First response:
{u'resource': u'https://outlook.office365.com', u'access_token': u'ey...Q', u'expires_in': u'3600', u'ext_expires_in': u'3600', u'token_type': u'Bearer', u'not_before': u'1469042069', u'expires_on': u'1469045969'}

Second response:
{u'timestamp': u'2016-07-20 19:19:29Z', u'trace_id': u'5670fc96-3b26-4a9a-9cfc-1d7f398df253', u'correlation_id': u'7c137ea4-a046-4003-8d29-b0890292f6f4', u'error_description': u'AADSTS70002: Error validating credentials. AADSTS50012: Client assertion contains an invalid signature.\r\nTrace ID: 5670fc96-3b26-4a9a-9cfc-1d7f398df253\r\nCorrelation ID: 7c137ea4-a046-4003-8d29-b0890292f6f4\r\nTimestamp: 2016-07-20 19:19:29Z', u'error': u'invalid_client', u'error_codes': [70002, 50012]}

Third response:
{u'resource': u'https://outlook.office365.com', u'access_token': u'ey...w', u'expires_in': u'3599', u'ext_expires_in': u'3600', u'token_type': u'Bearer', u'not_before': u'1469042070', u'expires_on': u'1469045970'}

**Comment by jasonjoh** [comment] 2016-07-25 15:29
@rsong6 Interesting. It sounds like the signing code may be intermittently producing an invalid signature. The signature of each client assertion in each token request is different, so you got a token find the first and third time because the signature in that case was valid.

If you can still reproduce this can you post some recent error responses (with the trace ID and correlations IDs). I'll ask the Azure AD folks to take a look and see if there's anything from the server side they can provide to help track it down.

**Comment by rsong6** [comment] 2016-07-26 17:05
@jasonjoh I verified each signature of the client assertion in each token request with the private key and it seems to be correct. So although I'm sending the correct signature, the server seems to throw an error randomly, and I can't find what's causing the issue.

**Comment by jasonjoh** [comment] 2016-11-29 17:44
Closing issue for now. If you can get more forensic data (response headers, trace ID, correlation ID, etc) then please reopen.

**Closed by jasonjoh** 2016-11-29 17:44 UTC
